# Generated by Django 4.1.3 on 2022-11-30 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0002_company_genre_language_location_alter_person_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='movie/series name')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='release date')),
                ('score', models.FloatField(blank=True, null=True, verbose_name='score')),
                ('duration', models.IntegerField(verbose_name='duration')),
                ('is_series', models.BooleanField(default=False, verbose_name='is series?')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='posters', verbose_name='poster')),
                ('trailer', models.CharField(blank=True, max_length=255, null=True, verbose_name='trailer link')),
                ('pg_rating', models.CharField(blank=True, max_length=150, null=True, verbose_name='PG rating')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='summary')),
                ('tagline', models.CharField(blank=True, max_length=255, null=True, verbose_name='tagline')),
                ('budget', models.IntegerField(blank=True, null=True, verbose_name='budget')),
                ('box_office', models.IntegerField(blank=True, null=True, verbose_name='box office')),
                ('company', models.ManyToManyField(to='movie_app.company', verbose_name='company')),
                ('genre', models.ManyToManyField(to='movie_app.genre', verbose_name='genre')),
                ('language', models.ManyToManyField(to='movie_app.language', verbose_name='language')),
                ('location', models.ManyToManyField(to='movie_app.location', verbose_name='location')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_app.media', verbose_name='media')),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField(default=0, verbose_name='duration')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='release date')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_app.season', verbose_name='season')),
            ],
        ),
        migrations.CreateModel(
            name='CastCrew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_app.media', verbose_name='media')),
                ('person', models.ManyToManyField(to='movie_app.person', verbose_name='person')),
                ('role', models.ManyToManyField(to='movie_app.role', verbose_name='role')),
            ],
        ),
    ]
