# Generated by Django 4.1.3 on 2022-11-30 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0003_media_season_episode_castcrew'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='episode name'),
        ),
        migrations.AddField(
            model_name='episode',
            name='number',
            field=models.IntegerField(blank=True, null=True, verbose_name='episode number'),
        ),
        migrations.AddField(
            model_name='season',
            name='number',
            field=models.IntegerField(blank=True, null=True, verbose_name='season number'),
        ),
        migrations.RemoveField(
            model_name='castcrew',
            name='person',
        ),
        migrations.RemoveField(
            model_name='castcrew',
            name='role',
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(max_length=150, verbose_name='language'),
        ),
        migrations.AddField(
            model_name='castcrew',
            name='person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='movie_app.person', verbose_name='person'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='castcrew',
            name='role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='movie_app.role', verbose_name='role'),
            preserve_default=False,
        ),
    ]
