# Generated by Django 4.1.3 on 2022-11-30 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0004_episode_name_episode_number_season_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='company',
            field=models.ManyToManyField(blank=True, null=True, to='movie_app.company', verbose_name='company'),
        ),
        migrations.AlterField(
            model_name='media',
            name='duration',
            field=models.IntegerField(blank=True, verbose_name='duration'),
        ),
        migrations.AlterField(
            model_name='media',
            name='genre',
            field=models.ManyToManyField(blank=True, null=True, to='movie_app.genre', verbose_name='genre'),
        ),
        migrations.AlterField(
            model_name='media',
            name='language',
            field=models.ManyToManyField(blank=True, null=True, to='movie_app.language', verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='media',
            name='location',
            field=models.ManyToManyField(blank=True, null=True, to='movie_app.location', verbose_name='location'),
        ),
    ]
