# Generated by Django 4.1.3 on 2022-12-01 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0006_alter_media_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='castcrew',
            name='media',
            field=models.ForeignKey(limit_choices_to={'is_series': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cast_crew', to='movie_app.media', verbose_name='media'),
        ),
        migrations.AlterField(
            model_name='castcrew',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cast_crew', to='movie_app.person', verbose_name='person'),
        ),
        migrations.AlterField(
            model_name='castcrew',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cast_crew', to='movie_app.role', verbose_name='role'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='movie_app.season', verbose_name='season'),
        ),
        migrations.AlterField(
            model_name='season',
            name='media',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='movie_app.media', verbose_name='media'),
        ),
    ]
