# Generated by Django 4.1.3 on 2022-12-01 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0007_alter_castcrew_media_alter_castcrew_person_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='castcrew',
            name='media',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cast_crew', to='movie_app.media', verbose_name='media'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='season',
            name='media',
            field=models.ForeignKey(limit_choices_to={'is_series': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='movie_app.media', verbose_name='media'),
        ),
    ]
