# Generated by Django 4.1.3 on 2022-12-11 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movie_app', '0010_watchlist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='castcrew',
            options={'verbose_name': 'cast_crew'},
        ),
        migrations.AlterModelOptions(
            name='watchlist',
            options={'verbose_name': 'watchlist', 'verbose_name_plural': 'watchlists'},
        ),
        migrations.CreateModel(
            name='MediaComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('comment', models.TextField(max_length=10000, verbose_name='comment')),
                ('comment_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='comment author')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='movie_app.media', verbose_name='media')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
