# Generated by Django 4.1.3 on 2022-12-11 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0011_alter_castcrew_options_alter_watchlist_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mediacomment',
            old_name='model',
            new_name='media',
        ),
    ]
